// src/app/contact/page.tsx
import FormBox from "@/components/FormBox";

export const metadata = {
  title: "Contact | Rohit Tokala",
  description: "Rohit Tokala's Contact page",
  openGraph: {
    type: "website",
    url: "https://tokala.dev/contact",
    title: "Contact | Rohit Tokala",
    description: "Rohit Tokala's contact page",
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact | Rohit Tokala",
    description: "Rohit Tokala's contact page",
    site: "@TokalaRohit",
  },
};

function ContactPage() {
  return (
    <div className=" h-screen bg-base-200 pb-16 w-full flex flex-col gap-4 items-center justify-center">
      <h2 className=" text-4xl font-medium">{"Contact Me"}</h2>
      <p className=" text-lg text-center mb-8">
        {
          "If you have any questions or would like to get in touch, please fill out the form below."
        }
      </p>
      <FormBox />
    </div>
  );
}

export default ContactPage;

// src/routes/contact/+page.svelte
<script>
	import { Card } from 'svelte-5-ui-lib';
</script>

<div class=" mt-8 flex h-[80vh] w-full max-w-4xl flex-col items-center gap-4 px-6">
	<h2 class=" mb-6 text-5xl font-extrabold uppercase tracking-wider text-primary-600">
		Contact Me
	</h2>
	<Card>
		<h3 class=" underline-offset-3 text-2xl font-semibold underline">Get in touch with me!</h3>
		<div class=" mt-4 flex w-full flex-col gap-4">
			<p>Email: <a href="mailto:rohit@tokala.dev" class="hover:underline">rohit@tokala.dev</a></p>
			<p>
				LinkedIn: <a href="https://linkedin.com/in/rohit-tokala" class="hover:underline"
					>rohit-tokala</a
				>
			</p>
			<p>X: <a href="https://x.com/TokalaRohit" class="hover:underline">@TokalaRohit</a></p>
		</div>
	</Card>
</div>
