// src/app/projects/page.tsx
import ProjectCard from "@/components/ProjectCard";
import RibbitThumb from "../../../public/ribbit-thumb.webp";
import SpredditThumb from "../../../public/spreddit-thumb.webp";
import NoteifyThumb from "../../../public/noteify-thumb.webp";
import NewsThumb from "../../../public/news-thumb.webp";
import PortfolioThumb from "../../../public/portfolio-thumb.webp";

function ProjectsPage() {
  return (
    <div className=" h-fit flex bg-base-300 gap-4 pb-4 flex-col items-center w-full">
      <h1 className=" font-semibold pt-6 text-3xl">
        {"Some of things I've built"}
      </h1>
      <p className=" pb-4 font-light max-w-xl">
        {
          "Check out some of the stuff I've built over the years. I'm always learning and trying new things. If you have any questions or want to chat, feel free to reach out!"
        }
      </p>
      <ul className="grid grid-flow-row items-stretch grid-cols-1 md:grid-flow-col xl:grid-rows-2 md:grid-rows-3 gap-10">
        <ProjectCard
          thumb={RibbitThumb}
          title="Ribbit"
          blurb="A fullstack Twitter-like web app with Auth"
          tags={[
            "Next.js",
            "TailwindCSS",
            "TypeScript",
            "NextAuth",
            "MySQL",
            "tRPC",
          ]}
          gitLink="https://github.com/rtokala14/ribbit"
          liveLink="https://ribbit-sooty.vercel.app/"
        />
        <ProjectCard
          thumb={SpredditThumb}
          title="Spreddit"
          blurb="A fullstack Reddit-like web app with Auth"
          tags={[
            "Next.js",
            "TailwindCSS",
            "TypeScript",
            "NextAuth",
            "PostgreSQL",
            "tRPC",
          ]}
          gitLink="https://github.com/rtokala14/spreddit-t3"
          liveLink="https://spreddit-t3.vercel.app/"
        />
        <ProjectCard
          thumb={PortfolioThumb}
          title="Portfolio"
          blurb="This Website! Built with Next13"
          tags={["Next.js 13", "TailwindCSS", "TypeScript", "DaisyUI"]}
          gitLink="https://github.com/rtokala14/personal-portfolio"
          liveLink="https://tokala.dev"
        />
        <ProjectCard
          thumb={NoteifyThumb}
          title="Note-ify"
          blurb="A fullstack note-taking built using Firebase as a backed"
          tags={[
            "React",
            "TailwindCSS",
            "Vite",
            "Firebase",
            "TypeScript",
            "React Router",
            "ShadcnUI",
          ]}
          gitLink="https://github.com/rtokala14/firebase-notetaking"
          liveLink="https://firebase-notetaking.vercel.app/"
        />
        <ProjectCard
          thumb={NewsThumb}
          title="The Toks News"
          blurb="A fullstack news app built using Next.js and NewsAPI"
          tags={["Next.js", "TailwindCSS", "TypeScript", "GraphQL", "Stepzen"]}
          gitLink="https://github.com/rtokala14/news-app"
          liveLink="http://news-app-chi-sandy.vercel.app/"
        />
      </ul>
    </div>
  );
}

export default ProjectsPage;

// src/routes/projects/+page.svelte
<script>
	import ProjectCard from '$lib/ProjectCard.svelte';
</script>

<div class=" my-8 flex min-h-[80vh] w-full max-w-4xl flex-col items-center gap-4 px-6">
	<h2 class=" text-5xl font-extrabold uppercase tracking-wider text-primary-600">My Projects</h2>
	<div class=" mt-6 flex flex-wrap items-center justify-center gap-6">
		<ProjectCard
			desc="A Website for a Restaurant in Dubai, fully optimized for SEO and for the web. Built using
		Sveltekit, styled with TailwindCSS, and deployed Vercel."
			title="HBH - Restaurant Website"
			src="/hbh.webp"
			alt="HBH Website Homepage"
			href="https://hbhdubai.com"
		/>
		<!-- Toks News -->
		<ProjectCard
			desc="A news aggregator built using NextJs, GraphQL with StepZen using the NewsAPI. "
			title="Toks News"
			src="/news.webp"
			alt="The Toks News Homepage"
			gitLink="https://github.com/rtokala14/news-app"
			href="https://news.tokala.dev"
		/>
		<!-- Note-ify -->
		<ProjectCard
			desc="An SPA created with React, using Firebase as the backend for the database and User Management."
			title="Noteify - A Note Taking App"
			src="/notes.webp"
			alt="Noteify Website Homepage"
			gitLink="https://github.com/rtokala14/firebase-notetaking"
			href="https://noteify.tokala.dev"
		/>
		<ProjectCard
			desc="A Twitter-like app built with NextJs Server components, Server Actions, and MySQL as the DB"
			title="Ribbit - Twitter Clone"
			src="/ribbit.webp"
			alt="Ribbit Homepage"
			gitLink="https://github.com/rtokala14/ribbit"
		/>
	</div>
</div>
